services:
  - type: web
    name: code-evaluator-frontend
    env: node
    buildCommand: cd my-app && npm install && NEXT_PUBLIC_API_URL=https://code-evaluator-backend.onrender.com npm run build
    startCommand: cd my-app && npm run start
    staticPublishPath: my-app/.next
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://code-evaluator-backend.onrender.com
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
